# Generated by Django 4.1.4 on 2022-12-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_alter_article_title_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел статьи', 'verbose_name_plural': 'Разделы статьи'},
        ),
    ]
